### ISSUE TITLE
Pre blocks overflow off of the main container

### ISSUE THREAD

**Issue by jacobmischka** [now-examples/next-news#16]
![image](https://cloud.githubusercontent.com/assets/3939997/24409368/a0332af2-1395-11e7-96ed-2b1099a117b5.png)

**Comment by rauchg** [comment]
I think we fixed this with the other PR?

**Comment by jacobmischka** [comment]
Yes, it shouldn't wrap off the page now with #15, though the styling is still different than vanilla HN which is what #17 aimed to fix. #17 isn't necessarily required now but it can still be merged if people like the styling better, up to you!
